data_dir: "data/market_data"
market_data_file_path: 'data/market_data/2020-01-01 to 2021-01-10.csv'

start_date: "2015-01-01"
cutoff_date: "2023-01-01"
end_date: "2024-03-15"

drop_features: ['Ticker', 'Volume', 'EPS Estimate', 
                'Reported EPS', 'Adj Close',
                'period_max_price', 'period_min_price',
                'period_max_price_pct', 'period_min_price_pct']
categorical_features: []
features_to_lag: ['pct_change']


targets: ['period_max_price_pct']
# targets: ['period_max_price_pct', 'period_min_price_pct']

target_outlier_threshold: [-30, 100]      # threshold for target (pct change)
